apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-limit-range
spec:
  limits:
  -
    default:
      memory: 1024Mi
      cpu: "2"
    defaultRequest:
      memory: 750Mi
      cpu: "1.5"
    type: Container
